# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wargame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[(b'tie', b'tie'), (b'player_a_won', b'Player A won'), (b'player_b_won', b'Player B won')], max_length=16)),
                ('course', models.TextField()),
                ('ai_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_a', to='wargame.ShipAi')),
                ('ai_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_b', to='wargame.ShipAi')),
            ],
        ),
    ]
