# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wargame', '0002_contest_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='result',
            new_name='outcome',
        ),
        migrations.AddField(
            model_name='match',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wargame.Contest'),
            preserve_default=False,
        ),
    ]
