# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargame', '0004_contest_results_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipai',
            name='representant',
            field=models.BooleanField(default=False),
        ),
    ]
