# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wargame', '0005_shipai_representant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('challanged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challanged', to=settings.AUTH_USER_MODEL)),
                ('challanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challangers', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wargame.Match')),
            ],
        ),
    ]
