# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wargame', '0006_challange'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challange',
            new_name='Challenge',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='challanged',
            new_name='challenged',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='challanger',
            new_name='challenger',
        ),
    ]
