# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wargame', '0008_auto_20160803_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ai_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ai_b',
        ),
        migrations.AddField(
            model_name='match',
            name='logic_a',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='logic_b',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player_a',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matches_a', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player_b',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matches_b', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
