# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargame', '0009_auto_20160803_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ai_name_a',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='ai_name_b',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
